spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hr
    username: postgres
    password: Trinigan49
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active:
    - smart
    
  thymeleaf:
    cache: false

  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

hr:
  salary:
    def:
      percent: 5
    smart:
      low: 1
      mid: 2.5
      high: 5
      lowPercent: 1
      midPercent: 2
      highPercent: 5